### ISSUE TITLE
Empty readme

### ISSUE THREAD

**Issue by ffigari** [jcbasso/json2yaml#1]
How am I suposed to know how to use this project with an empty readme file?
Pls fix

**Comment by nacho692** [comment]
Yeh yeh we are working on it

**Comment by ffigari** [comment]
You better do

**Comment by ffigari** [comment]
I see it was solved cfd91dee45522e08d0e8404dc113df98fd088add
Thanks!

**Comment by jcbasso** [comment]
Thanks for the feedback @ffigari .
We are going to take our hands on the matter!
